name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: echo "No tests yet, skipping..."

      - name: Run Tests again this is dummy test jobs
        run: echo "this is dummy test helloooo"

      - name: Deploy to Render (or Vercel/Heroku)
        run: echo "Deployment Step (Replace with actual hosting provider command)"
